sudo: 'required'
language: go
services:
- 'docker'
go:
- '1.8'
before_install:
- sudo apt install --only-upgrade docker-engine -y
script:
- docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
- make images
- make push-images
notifications:
  email: false
